TomaszWojciechowskiLab5/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TomaszWojciechowskiLab5.Models
{
    public class Movie
    {
        public int ID { get; set; }

        [Display(Name="Nazwa")]
        public string Name { get; set; }
        
        [Display(Name="Data")]
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }


    }
}

TomaszWojciechowskiLab5/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TomaszWojciechowskiLab5.Models;

namespace TomaszWojciechowskiLab5.Controllers
{
    public class MovieController : Controller
    {
        //
        // GET: /Movie/

        public LibraryDbContext context = new LibraryDbContext();

        public ActionResult Index()
        {
            Movie movie = (from mov in context.Movies
                           select mov).FirstOrDefault();

            return View(new Movie() { ReleaseDate = DateTime.Now });
        }

        public ActionResult ShowAll()
        {


            var query = (from mov in context.Movies
                         select mov).ToList();
            return View(query);
        }

        public ActionResult AddNewMovie(Movie newMovie)
        {
            context.Movies.Add(newMovie);
            context.SaveChanges();

            return RedirectToAction("ShowAll");
        }

        [HttpPost]
        public ActionResult DeleteById(int movieId)
        {
            context.Movies.Remove(context.Movies.Find(movieId));
            context.SaveChanges();

            return RedirectToAction("ShowAll");
        }

        public ActionResult UpdateById(int id)
        {
            var query = (from mov in context.Movies
                         where mov.ID == id
                         select mov).FirstOrDefault();
            return View(query);
        }

        [HttpPost]
        public ActionResult EditMovie(Movie editedMovie)
        {
            var movie = (from mov in context.Movies
                         where mov.ID == editedMovie.ID
                         select mov).FirstOrDefault();
            movie.Name = editedMovie.Name;
            movie.ReleaseDate = editedMovie.ReleaseDate;
            context.SaveChanges();

            return RedirectToAction("ShowAll");
        }
    }
}

TomaszWojciechowskiLab5/Views/Movie/Index.cshtml
@model TomaszWojciechowskiLab5.Models.Movie
@{
    ViewBag.Title = "Index";
}

<h2>Tytuł storny, nagłówek</h2>
<div>
    @using (Html.BeginForm("AddNewMovie", "Movie", FormMethod.Post))
    {
        @Html.DisplayNameFor(model => model.Name);
        @Html.EditorFor(Model => Model.Name);
        @Html.DisplayNameFor(model => model.ReleaseDate);
        @Html.EditorFor(Date => Date.ReleaseDate);
        <input type="submit" value="Wyślij"/>
    }
</div>

TomaszWojciechowskiLab5/Views/Movie/ShowAll.cshtml
@model List<TomaszWojciechowskiLab5.Models.Movie>
@{
    ViewBag.Title = "ShowAll";
}
@Html.Partial("~/Views/Movie/_AddNewMovieModal.cshtml")
@Html.Partial("~/Views/Movie/_EditMovieModal.cshtml")

<h2>Wszystkie filmy</h2>

<div>
    <button id="add_new_movie_button" class="btn btn-default">Dodaj nowy film</button>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th class="col-md-1">
                    Id
                </th>
                <th class="col-md-4">
                    Nazwa
                </th>
                <th class="col-md-3">
                    Data
                </th>
                <th class="col-md-4">
                    Akcje
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var item in Model)
                {
                    <tr id="@item.ID">
                        <td>@item.ID</td>
                        <td>@item.Name</td>
                        <td>@item.ReleaseDate.ToShortDateString()</td>
                        <td>
                            <button id="edit @item.ID @item.ReleaseDate.ToShortDateString() @item.Name" class="btn btn-primary edit">Edytuj</button>
                            <button id="delete @item.ID" class="btn btn-danger delete">Usuń</button>
                        </td>
                    </tr>
                }
            }
        </tbody>

    </table>

</div>
<script type="text/javascript">
    $(document).ready(function () {
        // obsługa przycisku add new movie
        $('#add_new_movie_button').click(function () {
            $('#add_movie_modal').modal('show');
        });
        //obsługa delete
        $('.delete').click(function () {
            var id = $(this).prop('id').substring(7);
            $.ajax({
                url: "/Movie/DeleteById",
                type: "POST",
                data: { movieId: id },
                success: function () {
                    $('#' + id).remove();
                },
                error: function () {
                    alert("Nie udało się!");
                }
            });
        });
        // obsługa edit
        $('.edit').click(function () {
            var str = $(this).prop('id').substring(5);
            var id = str.split(" ", 1);
            var date = str.split(" ", 2)[1];
            var index = str.indexOf(date) + date.length + 1;
            var name = str.substring(index);
            $('#edit_movie_modal').modal('show');
            $('#EditReleaseDate').val(date);
            $('#EditId').val(id);
            $('#EditName').val(name);
        });
    })

</script>

TomaszWojciechowskiLab5/Views/Movie/UpdateById.cshtml
@model TomaszWojciechowskiLab5.Models.Movie
@{
    ViewBag.Title = "UpdateById";
}

<h2>UpdateById</h2>

@Html.BeginForm("Save", "Movie", FormMethod.Post)
{
@Html.HiddenFor(Model => Model.ID)
@Html.DisplayNameFor(Model => Model.Name)
@Html.EditorFor(Model => Model.Name)
@Html.DisplayNameFor(Model => Model.ReleaseDate)
@Html.EditorFor(Model => Model.ReleaseDate)
<input type="submit" value="Zapisz">
}

TomaszWojciechowskiLab5/Views/Movie/_AddNewMovieModal.cshtml
<div class="modal fade" id="add_movie_modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Dodaj film</h4>
            </div>
            @using (Html.BeginForm("AddNewMovie", "Movie", FormMethod.Post))
            {
            <div class="modal-body">

                <table class="table tab-content">
                    <tr>
                        <td>Nazwa</td>
                        <td><input type="text" name="Name" /></td>
                    </tr>
                    <tr>
                        <td>Data</td>
                        <td><input type="date" name="ReleaseDate" value="@DateTime.Now.ToShortDateString()" /></td>
                    </tr>
                </table>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                <input type="submit" class="btn btn-primary" value="Dodaj" />

            </div>
            }
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

TomaszWojciechowskiLab5/Views/Movie/_EditMovieModal.cshtml
<div class="modal fade" id="edit_movie_modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Edytuj film</h4>
            </div>
            @using (Html.BeginForm("EditMovie", "Movie", FormMethod.Post))
            {
                <div class="modal-body">

                    <table class="table tab-content">
                        <tr>
                            <td>Nazwa</td>
                            <td><input type="text" id="EditName" name="Name" /></td>
                        </tr>
                        <tr>
                            <td>Data</td>
                            <td><input type="date" id="EditReleaseDate" name="ReleaseDate" /></td>
                        </tr>
                    </table>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                    <input type="submit" class="btn btn-primary" value="Zapisz" />
                    <input type="hidden" value="" id="EditId" name="Id"/>
                </div>
            }
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->